version: '3.9'
name: tmdad
services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      DATABASE_NAME: ${DATABASE_NAME}
    volumes:
      - ./database/init-user-db.sh:/docker-entrypoint-initdb.d/init-user-db.sh
      - ./database/data:/var/lib/postgresql/data
  
  gateway:
    image: nginx
    restart: always
    ports:
      - 80:80
    volumes:
      - ./gateway/nginx.conf.template:/etc/nginx/nginx.conf.template
      - ./static:/usr/share/nginx/html
    environment:
      BACKEND_SERVER: ${BACKEND_SERVER}
      BACKEND_PORT: ${BACKEND_PORT}
      MINIO_SERVER: ${MINIO_SERVER}
      MINIO_PORT: ${MINIO_PORT}
    command: ["/bin/bash", "-c", "envsubst '$${BACKEND_SERVER} $${BACKEND_PORT} $${MINIO_SERVER} $${MINIO_PORT}' < /etc/nginx/nginx.conf.template > /etc/nginx/nginx.conf && nginx -g 'daemon off;'"]

  minio:
    image: minio/minio
    restart: always
    ports:
      - "9001:9001"
    volumes:
      - ./minio_data:/data
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
    command: server --console-address ":9001" /data

  rabbitmq:
    image: rabbitmq:3-management
    restart: always
    hostname: 'dev-rabbitmq'
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_DEFAULT_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_DEFAULT_PASS}
    volumes:
      - ./rabbit_data:/var/lib/rabbitmq/mnesia/
    ports:
      - "15672:15672"

  chat-backend:
    image: eclipse-temurin:17-jdk-alpine
    restart: always
    volumes:
      - ./websockets/build/libs/websockets-0.0.1.jar:/app.jar
      - ./websockets/docker_run.sh:/run.sh
    depends_on:
      - db
      - minio
      - rabbitmq
    environment:
      CUSTOM_RABBITMQ_HOST: ${RABBITMQ_HOST}
      CUSTOM_MINIO_ENDPOINT: ${MINIO_SERVER}
      CUSTOM_MINIO_PORT: ${MINIO_PORT}
      CUSTOM_MINIO_ACCESSKEY: ${MINIO_ROOT_USER}
      CUSTOM_MINIO_SECRETKEY: ${MINIO_ROOT_PASSWORD}
      SPRING_DATASOURCE_URL: jdbc:postgresql://db/${DATABASE_NAME}
      SPRING_DATASOURCE_USERNAME: ${POSTGRES_USER}
      SPRING_DATASOURCE_PASSWORD: ${POSTGRES_PASSWORD}
    command: ["/bin/sh", "run.sh"]

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080