version: '3.9'
name: tmdad
services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: tmdad
      POSTGRES_PASSWORD: tmdad
      DATABASE_NAME: tmdad_db
    ports:
      - 5432:5432
    volumes:
      - ./database/init-user-db.sh:/docker-entrypoint-initdb.d/init-user-db.sh
      - ./database/data:/var/lib/postgresql/data

  adminer:
    image: adminer
    restart: always
    ports:
      - 8085:8080
  
  frontend:
    image: nginx
    restart: always
    ports:
      - 8080:80
    volumes:
      - ./gateway/nginx.conf:/etc/nginx/nginx.conf
      - ./static:/usr/share/nginx/html
