version: '3.9'
name: tmdad
services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: tmdad
      POSTGRES_PASSWORD: tmdad
      DATABASE_NAME: tmdad_db
    ports:
      - 5432:5432
    volumes:
      - ./database/init-user-db.sh:/docker-entrypoint-initdb.d/init-user-db.sh
      - ./database/data:/var/lib/postgresql/data

  adminer:
    image: adminer
    restart: always
    ports:
      - 8085:8080
  
  gateway:
    image: nginx
    restart: always
    ports:
      - 8080:80
      - 9000:9000
    volumes:
      - ./gateway/nginx.conf:/etc/nginx/nginx.conf
      - ./static:/usr/share/nginx/html

  minio:
    image: minio/minio
    ports:
      - "9001:9001"
      - "9999:9000"
    volumes:
      - ./minio_data:/data
    environment:
      MINIO_ROOT_USER: tmdad
      MINIO_ROOT_PASSWORD: tmdad#tmdad#tmdad
    command: server --console-address ":9001" /data

  rabbitmq:
    image: rabbitmq:3-management
    hostname: 'dev-rabbitmq'
    environment:
      RABBITMQ_DEFAULT_USER: tmdad
      RABBITMQ_DEFAULT_PASS: tmdad
    volumes:
      - ./rabbit_data:/var/lib/rabbitmq/mnesia/
    ports:
      - "5672:5672"
      - "15672:15672"